---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: w
  name: w
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: w
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: w
  name: w
spec:
  replicas: 2
  selector:
    matchLabels:
      app: w
  template:
    metadata:
      labels:
        app: w
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: x
  name: x
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: x
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: x
  name: x
spec:
  replicas: 2
  selector:
    matchLabels:
      app: x
  template:
    metadata:
      labels:
        app: x
    spec:
      containers:
        - image: httpd
          name: apache
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: y
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: w
            port:
              number: 80
      - path: /apache
        pathType: Prefix
        backend:
          service:
            name: x
            port:
              number: 8080
---

